version: "3.8"

services:
    keycloak:
      image: quay.io/keycloak/keycloak:26.1.0
      environment:
        - KC_BOOTSTRAP_ADMIN_USERNAME=admin
        - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      command: start-dev
      ports:
        - "8080:8080"